[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    {access = "read", path = "./broadcast"},
    {access = "read", path = "./reports"}
]

[invariant]
runs = 64
depth = 300
fail_on_revert = true

[profile.deep.invariant]
runs = 512
depth = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
